[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "online_retail_prediction"
version = "0.0.1"
description = "End to End ML pipeline to predict purchase intent from online retail sessions"
authors = [
  { name = "Team_2_SKU_YOU_LATER_MMA" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.11.0"
dependencies = [
    "joblib",
    "lightgbm",
    "loguru",
    "matplotlib",
    "numpy",
    "pandas",
    "python-dotenv",
    "scikit-learn",
    "seaborn",
    "shap",
    "tqdm",
    "typer",
    "xgboost",
]

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyterlab",
    "matplotlib",
    "mkdocs",
    "notebook",
    "pytest",
    "ruff",
    "streamlit",
]


[tool.ruff]
line-length = 99
src = ["online_retail_prediction"]
include = ["pyproject.toml", "online_retail_prediction/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["online_retail_prediction"]
force-sort-within-sections = true
